add email, SignIn and SignUp ui, register user
Redvin-dt/Bober pull request #8
Opened 2024-03-13 02:32 UTC by romanpovol

2024-03-13 22:38 UTC, Redvin-dt requested changes

2024-03-13 22:38 UTC, Redvin-dt commented on Client/app/src/main/java/ru/hse/client/SignInActivity.kt
> +            if (password.length <= 3) {
Mb write some more validation, such as check that it's hasn't {", '} etc

2024-03-13 22:38 UTC, Redvin-dt commented on Client/app/src/main/java/ru/hse/client/SignInActivity.kt
> +            val URlGetUser: String = ("http://" + getString(R.string.IP) + "/users/userByLogin").toHttpUrlOrNull()
What will be if somebody change endpoint and it return null?

2024-03-13 22:38 UTC, Redvin-dt commented on Client/app/src/main/java/ru/hse/client/SignInActivity.kt
> +                    if (response.code == 200) {
use response.ok() instead of equal with 200

2024-03-13 22:38 UTC, Redvin-dt commented on Client/app/src/main/java/ru/hse/client/SignInActivity.kt
> +                        Log.e("Info", "no such login/password")
i think better write response from server, because it can be error code 500, which means it's server error not client

2024-03-13 22:38 UTC, Redvin-dt commented on Client/app/src/main/java/ru/hse/client/SignUpActivity.kt
> +    return if (target == null || TextUtils.isEmpty(target)) {
does check on empty and null is needed?
matcher don't check this?

2024-03-13 22:38 UTC, Redvin-dt commented on Client/app/src/main/java/ru/hse/client/SignUpActivity.kt
> +        for (c in target) {
mb use regular expression like ^[\w\d_-]+$

2024-03-13 22:38 UTC, Redvin-dt commented on Client/app/src/main/java/ru/hse/client/SignUpActivity.kt
> +                    } else if (response.code == 400) {
not handling 500 error code and other, i think better use response.ok(), and write message from server

2024-03-13 22:38 UTC, Redvin-dt commented on server/src/main/java/ru/hse/server/repository/UserDatabaseRepository.java
> +            logger.debug("Find user={} by email={}", user, email);
lets use lower case

2024-03-13 22:38 UTC, Redvin-dt commented on server/src/main/java/ru/hse/server/service/UserService.java
> +        if (!userInfo.hasLogin() || !userInfo.hasPasswordHash()) {
need to check, does user has email, because you use getEmail after

2024-03-13 22:41 UTC, Redvin-dt commented
Wait approve from Yuri before merge

2024-03-14 18:33 UTC, Redvin-dt approved these changes

2024-03-14 18:33 UTC, Redvin-dt commented on Client/app/src/main/java/ru/hse/client/SignInActivity.kt
> +                if (passwordOriginal.length <= 3) {
isValidPassword

2024-03-14 18:33 UTC, Redvin-dt commented on Client/app/src/main/java/ru/hse/client/SignInActivity.kt
> +                        printErrorAboutBadUser()
printServerMessage instead, you don't know is it problem with user

2024-03-20 12:42 UTC, devcrocod reviewed
This is a very large pr, it could be separate into 2-3

2024-03-20 12:42 UTC, devcrocod commented on server/src/main/resources/TableCreation.sql
Is this the way to set a database? Usually publishing the database structure publicly is not good practice

2024-03-20 12:42 UTC, devcrocod commented on server/src/main/java/ru/hse/server/utils/ProtoSerializer.java
>                  .setMetaInfo(user.getMetaInfo())
where terminate op `build`?

2024-03-20 12:42 UTC, devcrocod commented on Client/app/src/main/java/ru/hse/client/SignInActivity.kt
> +            if (!isValidLogin(login)) {
if this is the main case of using validation functions, then it’s better to name it accordingly: `isNot...`

2024-03-20 12:42 UTC, devcrocod commented on Client/app/src/main/java/ru/hse/client/SignInActivity.kt
> +            okHttpClient.newCall(requestForGetUser).enqueue(object : Callback {
Why is the call not highlighted separately?

2024-03-20 12:42 UTC, devcrocod commented on Client/app/src/main/java/ru/hse/client/SignInActivity.kt
> +class SignInActivity : AppCompatActivity() {
This is a fairly complex class that includes a lot of actions. Think about how you can simplify it

2024-03-20 12:42 UTC, devcrocod commented on Client/app/src/main/java/ru/hse/client/SignUpActivity.kt
the same point as above
Even Github didn’t want to upload this file, there were too many lines

2024-03-26 18:21 UTC, romanpovol commented on server/src/main/java/ru/hse/server/utils/ProtoSerializer.java
>                  .setMetaInfo(user.getMetaInfo())
in line 82, no?

2024-03-30 15:05 UTC, YuriiFilatov approved these changes

2024-03-30 15:07 UTC, merged